# Generated by Django 3.0 on 2019-12-05 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_webapplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeturl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
