# Generated by Django 3.0 on 2019-12-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_webapplication', '0002_tweeturl_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweeturl',
            old_name='tweeturl',
            new_name='TweetUrl',
        ),
    ]
