# Generated by Django 3.0 on 2019-12-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_webapplication', '0003_auto_20191205_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweeturl',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
